import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import { Container } from "@/components/ui/container";
import { cookies } from "next/headers";
import { AuthProvider } from "@/context/auth-context";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin", "cyrillic"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieData = await cookies();
  const token = cookieData.get("jwt")?.value;

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${openSans.variable} antialiased`}>
        <AuthProvider token={token}>
          <Header />
          <Container>{children}</Container>
        </AuthProvider>
      </body>
    </html>
  );
}
