import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import { Container } from "@/components/ui/container";
import { getToken } from "@/lib/server-helpers";
import { fetchUser } from "@/api/strapi";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin", "cyrillic"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = await getToken();
  let user = null;
  if (token) {
    user = await fetchUser(token);
  }

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${openSans.variable} antialiased`}>
        <Header user={user} />
        <Container>{children}</Container>
      </body>
    </html>
  );
}
